apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: wordpress
spec:
  storageClassName: mariadb-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
